package com.duke.elliot.opicdi.audio_recoder

const val BUFFER_SIZE = 2048

const val DISPLAY_CHUNK_INTERVAL_MILLISECONDS = 10L
const val DISPLAY_TIMESTAMP_INTERVAL_MILLISECONDS = 2000L
const val RECORDING_TIME_INTERVAL_MILLISECONDS = 10L

const val TIMER_PATTERN = "mm:ss.SS"